site_name: Switchless docs
theme:
    name: null
    custom_dir: 'docs/custom_theme2/'
    sidebars: 
        - about
        - search
extra:
    logo: files/asyncauto-school-logo.png
    sidebars:
        - about
        - navigation
    homepage_sidebars:
        - about
        - navigation

nav:
    - Development:
        - Introduction: 'development/introduction.md'
        - Nodejs : 'development/nodejs.md'
        - Sailsjs : 'development/sailsjs.md'
        - Semantic UI : 'development/semantic.md'
        - Challenges: 'development/challenges/index.md'
        - Managing Timestamps: 'development/managing_timestamps.md'
    - Courses: 
        - Engineer - Level 1: 'courses/engineer_level_1.md'
        - Testing - Level 1: 'courses/testing_101.md'
    

plugins:
    - search
    # - encryptcontent:
        # global_password: 'your_password'

markdown_extensions:
  - toc:
      permalink: true
